error: use the latter error when combining
Since we are almost always matching to whitespace first, the error was
always "Welp, I wanted to see whitespace".